import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Preloader from "../components/Preloader";
import ClientNavWrapper from "../components/ClientNavWrapper";
import ClientFooterWrapper from "../components/ClientFooterWrapper"; // <- new

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const sora = localFont({
  src: [
    { path: "../fonts/Sora-Thin.ttf", weight: "100", style: "normal" },
    { path: "../fonts/Sora-ExtraLight.ttf", weight: "200", style: "normal" },
    { path: "../fonts/Sora-Light.ttf", weight: "300", style: "normal" },
    { path: "../fonts/Sora-Regular.ttf", weight: "400", style: "normal" },
    { path: "../fonts/Sora-Medium.ttf", weight: "500", style: "normal" },
    { path: "../fonts/Sora-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../fonts/Sora-Bold.ttf", weight: "700", style: "normal" },
    { path: "../fonts/Sora-ExtraBold.ttf", weight: "800", style: "normal" },
  ],
  variable: "--font-sora",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} antialiased`}>
        <Preloader />
        <ClientNavWrapper />
        {children}
        <ClientFooterWrapper /> {/* Footer hidden on login/register */}
      </body>
    </html>
  );
}
